server:
  port: 8080
  servlet:
    context-path: '/api'
spring:
  application:
    title: Ecotech
    version: 0.0.1
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-217-251-77.compute-1.amazonaws.com:5432/dbo0f612upe64q
    username: pleqapiolqflmv
    password: 4efa3aa0734b1749be80fd01a0beb93d994b98ea75bf0a20e8f798a34281795f
    continueOnError: true
  jpa:
    showSql: true
    ddlAuto: none
    database: default
