server:
  port: 8080
  servlet:
    context-path: '/api'
spring:
  application:
    title: Ecotech
    version: 0.0.1
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cjueve15mpss73dmj8i0-a.oregon-postgres.render.com:5432/ecotech_0yqx
    username: admin
    password: YTeE1sQQzwqgCGDbtOhJD8aTmNx8gpKe
    continueOnError: true
  jpa:
    showSql: true
    ddlAuto: none
    database: default
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

